<?php
session_start();
include("../config/db.php");

// 1. Secure Access Check: Ensure user is logged in and is a Local Authority official (Role 3 or 5)
if (!isset($_SESSION['role_id']) || ($_SESSION['role_id'] != 5 && $_SESSION['role_id'] != 3) || empty($_SESSION['user_id'])) {
    session_unset();
    session_destroy();
    header("Location: ../auth/login.php");
    exit();
}

$officer_id = $_SESSION['user_id'];
$success_msg = "";
$error_msg = "";
$generated_qr_url = ""; 

// 2. Form Processing
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    $event_title = isset($_POST['event_title']) ? trim($_POST['event_title']) : '';
    $description = isset($_POST['description']) ? trim($_POST['description']) : '';
    $event_date = isset($_POST['event_date']) ? trim($_POST['event_date']) : '';
    $start_time = isset($_POST['start_time']) ? trim($_POST['start_time']) : '';
    $end_time = isset($_POST['end_time']) ? trim($_POST['end_time']) : '';
    $location = isset($_POST['location']) ? trim($_POST['location']) : '';
    $required_volunteers = isset($_POST['required_volunteers']) ? (int)$_POST['required_volunteers'] : 0;
    
    $image_path = null; 

    if (empty($event_title) || empty($event_date) || empty($start_time) || empty($end_time) || empty($location) || $required_volunteers <= 0) {
        $error_msg = "Please fill out all fields with valid information.";
    } elseif (strtotime($event_date) < strtotime(date('Y-m-d'))) {
        $error_msg = "The event date cannot be in the past.";
    } elseif (strtotime($end_time) <= strtotime($start_time)) {
        $error_msg = "End time must be after the start time.";
    } else {
        
        if (isset($_FILES['event_image']) && $_FILES['event_image']['error'] === UPLOAD_ERR_OK) {
            $file_tmp = $_FILES['event_image']['tmp_name'];
            $file_name = $_FILES['event_image']['name'];
            $file_size = $_FILES['event_image']['size'];
            $file_ext = strtolower(pathinfo($file_name, PATHINFO_EXTENSION));
            
            $allowed_extensions = array("jpg", "jpeg", "png", "webp");
            
            if (!in_array($file_ext, $allowed_extensions)) {
                $error_msg = "Invalid file extension. Only JPG, JPEG, PNG, and WEBP files are allowed.";
            } elseif ($file_size > 5 * 1024 * 1024) {
                $error_msg = "Image size is too large. Maximum size allowed is 5MB.";
            } else {
                $upload_dir = "../uploads/";
                if (!is_dir($upload_dir)) {
                    mkdir($upload_dir, 0755, true);
                }
                
                $new_file_name = "event_" . time() . "_" . uniqid() . "." . $file_ext;
                $target_file = $upload_dir . $new_file_name;
                
                if (move_uploaded_file($file_tmp, $target_file)) {
                    $image_path = $target_file;
                } else {
                    $error_msg = "Failed to upload image. Please try again.";
                }
            }
        }

        if (empty($error_msg)) {
            $verification_token = bin2hex(random_bytes(16)); 

            $insert_query = "INSERT INTO volunteer_events (created_by, event_title, description, event_date, start_time, end_time, location, required_volunteers, event_image, verification_token, status) 
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'OPEN')";
            
            $stmt = mysqli_prepare($conn, $insert_query);
            if ($stmt) {
                mysqli_stmt_bind_param($stmt, "issssssiss", $officer_id, $event_title, $description, $event_date, $start_time, $end_time, $location, $required_volunteers, $image_path, $verification_token);
                
                if (mysqli_stmt_execute($stmt)) {
                    $success_msg = "Volunteer event successfully published and listed for community action!";
                    $generated_qr_url = "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=" . urlencode($verification_token);

                    $event_title = $description = $event_date = $start_time = $end_time = $location = "";
                    $required_volunteers = "";
                } else {
                    $error_msg = "Database Error: Could not save the event structure.";
                }
                mysqli_stmt_close($stmt);
            } else {
                $error_msg = "Internal Error: System failed to prepare data stream.";
            }
        }
    }
}

// 3. FETCH EXISTING EVENTS GENERATED BY THIS LA OFFICIAL
$events_list = [];
$list_query = "SELECT event_id, event_title, event_date, location, verification_token FROM volunteer_events WHERE created_by = ? ORDER BY event_date DESC";
$list_stmt = mysqli_prepare($conn, $list_query);
if ($list_stmt) {
    mysqli_stmt_bind_param($list_stmt, "i", $officer_id);
    mysqli_stmt_execute($list_stmt);
    $res = mysqli_stmt_get_result($list_stmt);
    while ($row = mysqli_fetch_assoc($res)) {
        $events_list[] = $row;
    }
    mysqli_stmt_close($list_stmt);
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Volunteer Opportunity</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f2f5f2; margin: 0; padding-bottom: 50px; }
        .header { background-color: #006064; color: white; padding: 20px; text-align: center; position: relative; }
        .back-btn { 
            position: absolute; top: 20px; left: 20px; 
            background-color: transparent; border: 2px solid white; color: white; 
            padding: 8px 15px; border-radius: 5px; 
            text-decoration: none; font-size: 14px; font-weight: bold; 
        }
        .back-btn:hover { background-color: white; color: #006064; }
        
        .form-section, .manage-section { width: 50%; min-width: 450px; margin: 40px auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0px 2px 8px rgba(0,0,0,0.1); }
        .form-section h2, .manage-section h2 { color: #006064; margin-top: 0; border-bottom: 2px solid #b2dfdb; padding-bottom: 10px; }
        
        .alert { padding: 12px; margin-bottom: 20px; border-radius: 5px; font-weight: bold; font-size: 14px; }
        .alert-success { background-color: #e8f5e9; color: #2e7d32; border-left: 5px solid #388e3c; }
        .alert-error { background-color: #ffebee; color: #c62828; border-left: 5px solid #d32f2f; }
        
        .form-group { margin-bottom: 18px; display: flex; flex-direction: column; }
        .form-row { display: flex; gap: 15px; }
        .form-row .form-group { flex: 1; }
        
        label { font-weight: bold; margin-bottom: 6px; color: #455a64; font-size: 14px; }
        input[type="text"], input[type="date"], input[type="time"], input[type="number"], input[type="file"], textarea {
            padding: 10px; border: 1px solid #ccc; border-radius: 5px; font-size: 14px; font-family: inherit; box-sizing: border-box; width: 100%;
        }
        input:focus, textarea:focus { border-color: #006064; outline: none; box-shadow: 0 0 5px rgba(0, 96, 100, 0.2); }
        textarea { resize: vertical; min-height: 100px; }
        
        .btn-submit { background-color: #006064; color: white; border: none; padding: 12px 20px; cursor: pointer; border-radius: 5px; font-weight: bold; font-size: 16px; width: 100%; margin-top: 10px; }
        .btn-submit:hover { background-color: #00363a; }

        .qr-card { background: #f0f7f7; border: 2px dashed #006064; border-radius: 8px; padding: 25px; margin-bottom: 25px; text-align: center; }
        .qr-card h3 { margin-top: 0; color: #00363a; }
        .qr-image { background: white; padding: 10px; border: 1px solid #ddd; border-radius: 5px; margin: 15px 0; display: inline-block; }
        .btn-print { background-color: #455a64; color: white; border: none; padding: 8px 15px; cursor: pointer; border-radius: 4px; font-weight: bold; font-size: 13px; margin-top: 5px; }
        .btn-print:hover { background-color: #263238; }

        /* Management Table styling */
        .event-table { width: 100%; border-collapse: collapse; margin-top: 15px; }
        .event-table th, .event-table td { padding: 10px; border: 1px solid #ddd; text-align: left; font-size: 14px; }
        .event-table th { background-color: #f5f5f5; color: #455a64; }
        .btn-action-qr { background-color: #0288d1; color: white; border: none; padding: 5px 10px; border-radius: 3px; cursor: pointer; text-decoration: none; font-size: 12px; font-weight: bold; }
        .btn-action-qr:hover { background-color: #01579b; }

        @media print {
            body { background: white; }
            .header, .form-section, .manage-section h2, .event-table, .btn-print, .back-btn { display: none !important; }
            .manage-section { box-shadow: none; padding: 0; margin: 0; width: 100%; }
            .qr-card { border: none; padding: 0; display: block !important; }
        }
    </style>
</head>
<body>

<div class="header">
    <a href="la_dash.php" class="back-btn">← Return to Dashboard</a>
    <h1>Environmental Action Center</h1>
    <p>Mobilize Community Support & Manage Local Volunteer Resources</p>
</div>

<?php if (!empty($generated_qr_url)): ?>
    <div class="form-section" style="margin-bottom: -20px; padding-bottom: 10px;">
        <div class="qr-card">
            <h3>🎟️ Created Event QR Generated Successfully</h3>
            <div class="qr-image">
                <img src="<?php echo $generated_qr_url; ?>" alt="Secure Attendance QR Code">
            </div>
            <br>
            <button type="button" class="btn-print" onclick="window.print()">🖨️ Print Poster Now</button>
        </div>
    </div>
<?php endif; ?>

<div class="form-section">
    <h2>Post New Volunteer Opportunity</h2>
    
    <?php if (!empty($success_msg)): ?>
        <div class="alert alert-success"><?php echo $success_msg; ?></div>
    <?php endif; ?>
    <?php if (!empty($error_msg)): ?>
        <div class="alert alert-error"><?php echo $error_msg; ?></div>
    <?php endif; ?>

    <form method="POST" action="" enctype="multipart/form-data">
        <div class="form-group">
            <label for="event_title">Event Title / Campaign Objective:</label>
            <input type="text" id="event_title" name="event_title" placeholder="e.g., Kelani River Basin Cleanup Drive" value="<?php echo isset($event_title) ? htmlspecialchars($event_title) : ''; ?>" required>
        </div>

        <div class="form-group">
            <label for="description">Detailed Description & Instructions:</label>
            <textarea id="description" name="description" placeholder="Provide event instructions, safety tips, required gear, or general tasks expected..." required><?php echo isset($description) ? htmlspecialchars($description) : ''; ?></textarea>
        </div>

        <div class="form-group">
            <label for="event_image">Event Header Image (Optional):</label>
            <input type="file" id="event_image" name="event_image" accept="image/png, image/jpeg, image/jpg, image/webp">
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="event_date">Target Date:</label>
                <input type="date" id="event_date" name="event_date" min="<?php echo date('Y-m-d'); ?>" value="<?php echo isset($event_date) ? htmlspecialchars($event_date) : ''; ?>" required>
            </div>
            <div class="form-group">
                <label for="required_volunteers">Volunteers Requested:</label>
                <input type="number" id="required_volunteers" name="required_volunteers" min="1" placeholder="Ex: 25" value="<?php echo isset($required_volunteers) ? htmlspecialchars($required_volunteers) : ''; ?>" required>
            </div>
        </div>

        <div class="form-row">
            <div class="form-group">
                <label for="start_time">Start Time:</label>
                <input type="time" id="start_time" name="start_time" value="<?php echo isset($start_time) ? htmlspecialchars($start_time) : ''; ?>" required>
            </div>
            <div class="form-group">
                <label for="end_time">Estimated End Time:</label>
                <input type="time" id="end_time" name="end_time" value="<?php echo isset($end_time) ? htmlspecialchars($end_time) : ''; ?>" required>
            </div>
        </div>

        <div class="form-group">
            <label for="location">Meeting Location / Physical Address:</label>
            <input type="text" id="location" name="location" placeholder="e.g., Regional Dumping Ground Site, Sector 4 Council Depot" value="<?php echo isset($location) ? htmlspecialchars($location) : ''; ?>" required>
        </div>

        <button type="submit" class="btn-submit">Publish Opportunity</button>
    </form>
</div>

<div class="manage-section">
    <h2>Your Posted Campaigns & Attendance Keys</h2>
    
    <div id="reprintQrContainer" class="qr-card" style="display:none;">
        <h3 id="reprintTitle">Official Venue Attendance Verification Token</h3>
        <div class="qr-image">
            <img id="reprintQrImg" src="" alt="QR Verification Code">
        </div>
        <br>
        <button type="button" class="btn-print" onclick="window.print()">🖨️ Print This Poster</button>
        <button type="button" class="btn-print" style="background-color:#78909c;" onclick="closeReprintCard()">Cancel</button>
    </div>

    <?php if (empty($events_list)): ?>
        <p style="color:#666; font-size:14px;">You haven't posted any volunteer events yet.</p>
    <?php else: ?>
        <table class="event-table">
            <thead>
                <tr>
                    <th>Campaign Objective</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($events_list as $row): ?>
                    <tr>
                        <td><strong><?php echo htmlspecialchars($row['event_title']); ?></strong></td>
                        <td><?php echo date("Y-m-d", strtotime($row['event_date'])); ?></td>
                        <td>
                            <button type="button" class="btn-action-qr" 
                                    onclick="showOldQr('<?php echo urlencode($row['verification_token']); ?>', '<?php echo htmlspecialchars(addslashes($row['event_title'])); ?>')">
                                🔍 View QR
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
</div>

<script>
function showOldQr(token, title) {
    var qrUrl = "https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=" + token;
    document.getElementById('reprintQrImg').src = qrUrl;
    document.getElementById('reprintTitle').innerText = "🎟️ Attendance QR: " + title;
    document.getElementById('reprintQrContainer').style.display = "block";
    
    document.getElementById('reprintQrContainer').scrollIntoView({ behavior: 'smooth' });
}

function closeReprintCard() {
    document.getElementById('reprintQrContainer').style.display = "none";
}
</script>

</body>
</html>